config/routes.rb
Rails.application.routes.draw do
  post '/nuevomarca' => 'branding_products#nuevomarca'
  post '/nuevocategoria' => 'category_products#nuevocategoria'

    get '/add' => 'orders#add_product'
    get '/orders' => 'orders#index'
    get '/facturas' => 'orders#invoices'
    get '/validate' => 'orders#validate'
    
  resources :orders
  resources :products
  
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'pages#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#index', as: :unauthenticated_root
    end
  end

end

app/models/branding_product.rb
class BrandingProduct < ActiveRecord::Base
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	serialize :productos, Hash
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_attached_file :foto, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "http://empresacolombinanathalia.weebly.com/uploads/2/8/1/4/28148007/s599866822382417415_p11_i1_w322.jpeg"
	validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => {email: false, numeroidentificacion: true}
  validates :numeroidentificacion, uniqueness: true
    def email_required?
    false
  end

  def email_changed?
    false
  end

  has_many :orders
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

      def configure_permitted_parameters
          devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:password, :current_password, :nombre, :tipoidentificacion, :numeroidentificacion, :nombreestablecimiento, :telefono, :celular, :barrio, :direccion) }
          devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:password, :current_password, :nombre, :tipoidentificacion, :numeroidentificacion, :nombreestablecimiento, :telefono, :celular, :barrio, :direccion) }
      end
end

app/controllers/branding_products_controller.rb
class BrandingProductsController < ApplicationController
  def nuevomarca

	@marca = params[:marca]
	BrandingProduct.create(marca: @marca)
	redirect_to new_product_path

  end
end

app/controllers/category_products_controller.rb
class CategoryProductsController < ApplicationController
  def nuevocategoria

	@categoria = params[:categoria]
	CategoryProduct.create(categoria: @categoria)
	redirect_to new_product_path

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  before_action :permisos_admin, only: [:show, :invoices, :validate]

  def permisos_admin
    unless user_signed_in? and current_user.admin == true
      redirect_to 'products'
    end
  end
  
  def add_product
    $id = params[:id]
    $cantidad = params[:cant]

    if session[:cart] then
      cart = session[:cart]
    else
      session[:cart] = {}
      cart = session[:cart]
    end
      cart[$id] = $cantidad

    redirect_to '/products'
  end

  # GET /orders
  # GET /orders.json
  def index
    if session[:cart] then
      @cart = session[:cart]
      $cart = @cart

    else
      @cart = {}
    end
  end

  def show
    $id = params[:id]
    @order = Order.find_by_id($id)
  end

  # POST /orders
  # POST /orders.json
  def new
    @compra = current_user.orders.create(productos: session[:cart])
    session[:cart] = {}
    flash[:notice] = "Su pedido fue exitoso, estara en la puerta de su casa en menos de 72 horas"
    redirect_to '/products'
  end

  def invoices
    @facturas = Order.all
  end

  def validate
    $id = params[:id]
    @order = Order.find_by_id($id).update(visto: true)
    redirect_to '/facturas'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :permisos_admin, only: [:new, :create, :edit, :update, :destroy]
    

  def permisos_admin
    unless user_signed_in? and current_user.admin == true
      redirect_to 'products'
    end
  end
  # GET /products
  # GET /products.json
  def index
    @marca = params[:marca]
    @categoria = params[:categoria]
    @ask = params[:ask]

    if @ask
      @products = Product.where("nombre LIKE ?", "%#{@ask}%")
      if @products.presence
        @products
      else
        flash[:notice] = "No se encontro el producto por la referencia #{@ask}."
        redirect_to '/products'
      end
    elsif @marca or @categoria
      @products = Product.where( "marca = '#{@marca}' OR categoria = '#{@categoria}'" )
    else
      @products = Product.all
    end
    @category = CategoryProduct.all
    @branding = BrandingProduct.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path, notice: 'El Producto fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to products_path, notice: 'El producto fue modificado exitosamente.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:codigo, :nombre, :categoria, :marca, :precio, :foto, :url_photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/branding_products_helper.rb
module BrandingProductsHelper
end

app/helpers/category_products_helper.rb
module CategoryProductsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/branding_products/new.html.erb
<h1>BrandingProducts#new</h1>
<p>Find me in app/views/branding_products/new.html.erb</p>

app/views/category_products/new.html.erb
<h1>CategoryProducts#new</h1>
<p>Find me in app/views/category_products/new.html.erb</p>

app/views/layouts/_navigation.html.erb
<header class="indexheader headerall"> <!-- Cabezera del Homepage -->
  <figure>
    <h2>EL PROVEEDOR</h2>
  </figure>
  <nav class="navigation">
    <ul>
      <li>
        <% if session[:cart] %>
          <%= link_to orders_path do %>
            <span class="icon-shopping-cart"></span>
            <p>Pedido</p>
            <div class="triangulo_izq"></div>
            <div class="count">
              <strong><%= cantidad = session[:cart].count %></strong>
            </div>
          <% end %>
        <% end %>
      </li>
      <li>
        <%= link_to products_path do %>
          <span class="icon-shop"></span><p> Productos</p>
        <% end %>
      </li>
      <li class="ingresar">
      	<% unless user_signed_in? %>
        	<%= link_to 'Ingresar Usuario', user_session_path %>
      	<% else %>
      		<%= link_to('Salir', destroy_user_session_path, :method => :delete) %>
      	<% end %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

  <title>El Proveedor</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,900,400italic|Lato:400,900' 
  rel='stylesheet' type='text/css'>
  <%= favicon_link_tag 'myicon.png'%>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
</head>
<body>
  <% if notice || alert %>
        <% if notice %>
        <div class="flash f-notice">
        <label><span id="cerrar">X</span></label>
          <p class="notice"><%= notice %></p>
        <% elsif alert %>
        <div class="flash f-alert">
        <label><span id="cerrar">X</span></label>
      	 <p class="alert"><%= alert %></p>
        <% else %>
        <% end %>
      </div>
<% end%>

<%= yield %>
<script type="text/javascript">
  <% if session[:cart] %>
    <% session[:cart].each do |key, value| %>
        document.getElementById("<%= key %>").className += " comprar";
    <% end %>
  <% end %>
</script>
<script type="text/javascript">
  $( "#user_session" ).click(function() {
  $( "#signboard" ).slideToggle( "slow" );
  });
</script>
<script type="text/javascript">
  $( "#cerrar" ).click(function() {
  $( ".flash" ).css( "display", "none" );
  });
</script>

<script type="text/javascript">
window.addEventListener("scroll", function(){
    if(document.body.scrollTop > 80){ 
    busqueda.classList.add('active-busqueda'); 
  }else{
    busqueda.classList.remove('active-busqueda'); 
  };
})
</script>

<script type="text/javascript">
filtro.addEventListener("click", function(){ filtros.classList.toggle('active-filtro'); });
</script>

<script type="text/javascript">
filtro.addEventListener("click", function(){ blank.classList.toggle('active-filtro'); });
</script>
<script type="text/javascript">
window.addEventListener("resize", function(){
var mediaquery = window.matchMedia("(max-width: 480px)");
  if (mediaquery.matches) {
      document.getElementById("myTd").colSpan = "1";
      document.getElementById("myTd1").colSpan = "1";
      document.getElementById("myTd2").colSpan = "1";
  } else {
    document.getElementById("myTd").colSpan = "2";
      document.getElementById("myTd1").colSpan = "2";
      document.getElementById("myTd2").colSpan = "2";
  }
});
</script>

  <!--Start of Tawk.to Script-->
  <script type="text/javascript">
  var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
  (function(){
  var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
  s1.async=true;
  s1.src='https://embed.tawk.to/5801305c277fb7280d9b250e/default';
  s1.charset='UTF-8';
  s1.setAttribute('crossorigin','*');
  s0.parentNode.insertBefore(s1,s0);
  })();
  </script>
  <!--End of Tawk.to Script-->

</body>
</html>

app/views/orders/index.html.erb
<nav>
  <%= render 'layouts/navigation' %>
</nav>
<div class="orders">
	<div class="order">
		<div class="sub-header">
			<div><h2><strong>Orden de Pedido</strong></h2></div>
			<ul>
				<li><strong>Cliente: </strong>Cliente Ocacional</li>
				<li><strong>Fecha: </strong><%= Time.now %></li>
			</ul>
		</div>
		<table>
				<tr class="td-head">
					<td>Articulos</td>
					<td>Cantidad</td>
					<td class="none">Precio Unitario</td>
					<td class="important-c">Total</td>
				</tr>
				<% total = 0 %>
			<% @cart.each do |id, cantidad| %>
				<tr class="order-list-product">
					<% product = Product.find_by_id(id) %>
					<td><%= product.nombre %></td>
					<td><%= cantidad %></td>
					<td class="none"><%= number_to_currency(product.precio, :unit => '$' ) %></td>
					<td class="important"><%= number_to_currency(product.precio * cantidad.to_i, :unit => '$' ) %></td>
					<td></td>
					<% total += (product.precio * cantidad.to_i) %>
				</tr>
			<% end %>
					<% iva = total.to_f * 0.16 %>
				<tr>
					<td id="myTd" colspan="2" class="colspan"></td>
					<td>Subtotal</td>
					<td class="important-c"><%= number_to_currency((total - iva).to_i, :unit => '$' ) %></td>
				</tr>
				<tr>
					<td id="myTd1" colspan="2" class="colspan"></td>
					<td>Iva (16%)</td>
					<td class="important-c"><%= number_to_currency(iva.to_i, :unit => '$' ) %></td>
				</tr>
				<tr>
					<td id="myTd2" colspan="2" class="colspan"></td>
					<td>Total</td>
					<td class="important-c"><%= number_to_currency(total, :unit => '$' ) %></td>
				</tr>
		</table>
		<%= link_to 'Comprar', new_order_path, class: 'btn' %>
	</div>
</div>

app/views/orders/invoices.html.erb
<nav>
  <%= render 'layouts/navigation' %>
</nav>
<section class="facturas">
	<% @facturas.each do |factura| %>
		<% @id = factura.user_id %>
		<% user = User.find_by_id(@id) %>
			<div class="card<% if factura.visto == true %> visto<% end %>">
				<a href="<%= "orders/#{factura.id}" %>">
				<span class="icon-archive" style="font-size: 50px"></span>
				<%= factura.id %>
				<%= user.nombre %>
				<%= user.numeroidentificacion %>
				</a>
				<%= form_tag({controller: "orders", action: "validate"}, :method => "get") do %>
				        <%= hidden_field_tag( :id , factura.id ) %>
				        <input type="submit" value="OK!" class="btn ok"></input>
			    <% end %>
			</div>
	<% end %>
</section>

app/views/orders/show.html.erb
<% total = 0 %>
<% @order.productos.each do |id, cantidad| %>
	<tr class="order-list-product">
		<% product = Product.find_by_id(id) %>
			<td><%= product.codigo %></td>
			<td><%= cantidad %></td>
			<td class="none"><%= number_to_currency(product.precio, :unit => '$' ) %></td>
			<td class="important"><%= number_to_currency(product.precio * cantidad.to_i, :unit => '$' ) %></td>
		<% total += (product.precio * cantidad.to_i) %>
	</tr>
<% end %>

app/views/pages/index.html.erb
<%= render 'layouts/navigation' %>
<section class="principal">
<h2>"Pronto veras mejoras, estamos alegres de tenerte"</h2>
<%= link_to 'Productos', products_path %>
</section>

app/views/products/_filters.html.erb
<%= form_tag("/products", method: "get") do %>
        <h3>Categorias</h3>
  <div>
        <% @category.each do |categoria| %>
          <% cat = categoria.categoria %>
          <%= label_tag("categoria_#{cat}", cat, class: 'radio') do %>
            <%= radio_button_tag(:categoria, cat, id: 'radio2') %>
            <span class="outer"><span class="inner"></span></span><%= cat %>
          <% end%>
        <% end %>
  </div>
        <h3>Marcas</h3>
  <div>
        <% @branding.each do |marca| %>
          <% mar = marca.marca %>
          <%= label_tag("marca_#{mar}", mar, class: 'radio') do %>
            <%= radio_button_tag(:marca, mar, id: 'radio2') %>
            <span class="outer"><span class="inner"></span></span><%= mar%>
          <% end%>
        <% end %>
  </div>
  <%= submit_tag("Filtrar", { :class => 'btn btn-filtrar' })%>
<% end %>
<header class="indexheader headerall nav-lateral">
  <nav class="navigation">
    <ul>
      <li class="ingresar">
        <% unless user_signed_in? %>
          <%= link_to 'Ingresar Usuario', user_session_path %>
        <% else %>
          <%= link_to('Salir', destroy_user_session_path, :method => :delete) %>
        <% end %>
      </li>
    </ul>
</header>
<header class="indexheader headerall nav-lateral">
  <nav class="navigation">
    <ul>
      <li class="ingresar">
        <% unless user_signed_in? %>
          <%= link_to 'Ingresar Usuario', user_session_path %>
        <% else %>
          <%= link_to('Salir', destroy_user_session_path, :method => :delete) %>
        <% end %>
      </li>
    </ul>
</header>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :codigo, placeholder: "Codigo",required: "" %>
  </div>
  <div class="field">
    <%= f.text_field :nombre, placeholder: "Nombre del producto",required: "" %>
  </div>
  <div class="field">
   <!-- <%= f.text_field :url_photo, placeholder: "url del producto",required: "" %>-->
  </div>
  <div class="field">
    <%= select_tag "categoria", options_from_collection_for_select(CategoryProduct.all, "categoria", "categoria"), prompt: "Categoria" %>
  </div>
  <div class="field">
    <%= select_tag "marca", options_from_collection_for_select(BrandingProduct.all, "marca", "marca"), prompt: "Marca" %>
  </div>
  <div class="field">
    <%= f.number_field :precio, placeholder: "$ Precio",required: "" %>
  </div>
  <div class="actions">
    <%= f.submit 'Guardar Producto', class: 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<section class="nuevo-producto">
	<h1>Editando Producto</h1>

	<%= render 'form' %>

	<br><em><%= link_to 'Ver Todos los productos', products_path %></em>
</section>

app/views/products/index.html.erb
<%= render 'layouts/navigation' %>
<section class="section-products">
	<div class="busqueda" id="busqueda">
		<div class="menu">
			<button id="filtro"><span class="icon-menu"></span></button>
		</div>
		<div class="search">

			<form class="form-buscar" action="/products" accept-charset="UTF-8" method="get">
		      <input name="utf8" type="hidden" value="✓">
		      <input type="text" name="ask" id="ask" value="" class="text-buscar" >
		      <button type="submit" class="btn-buscar-producto">Buscar</button>
		    </form>

		</div>
	</div>
	<div class="products">
		<div class="filtros blank" style="position: relative;" id="blank">
		</div>
		<div class="filtros" id="filtros">
			<%= render "filters" %>
		</div>
		<div class="productos">
			<% if user_signed_in? && current_user.admin == true %>
				<div class="product nuevo-producto">
					<%= link_to new_product_path do %>
						<span class="icon-circle-plus"> Nuevo Producto</span>
					<% end %>
				</div>
			<% end %>
			    <% @products.each do |product| %>
			    <div class="product" id="<%= product.id %>">
			    	<div class="foto-producto">
			    		<%= image_tag product.foto.url() %>
			    	</div>
			    	<div class="action-producto">
			    		<div class="inf-producto">
			    			<h2><%= product.nombre %></h2>
			    			<p><%= product.marca %></p>
			    			<h4><%= number_to_currency(product.precio, :unit => '$' ) %></h4>
			    		</div>
			    		<% if user_signed_in? && current_user.admin == true %>
				    		<div class="modificar">
				    			<%= link_to edit_product_path(product) do %>
				    				<span class="icon-tools"></span>
				    			<% end %>
				        		<%= link_to product, method: :delete, data: { confirm: 'Are you sure?' } do %>
				        			<span class="icon-eliminar"></span>
				        		<% end %>
				    		</div>
			    		<% else %>
				    		<div class="pedir">
			                  <%= form_tag({controller: "orders", action: "add_product"}, :method => "get", :class => 'form-pedido') do %>
				                  <%= hidden_field_tag( :id , product.id ) %>
				                  <%= number_field_tag :cant, :cantidad, class: "cantidad-producto", :placeholder => "und", :required => true, in: 1...100 %>
				                  <input type="submit" value="Comprar" class="btn-pedido"></input>
			                  <% end %>
				    		</div>
				    		<div class="comprado" style="display: none;"><h2>COMPRADO</h2></div>
			    		<% end %>
			    	</div>
			    </div>
			    <% end %>
		</div>
	</div>
</section>

app/views/products/new.html.erb
<section class="nuevo-producto">

	<div class="add-producto">
		<%= form_tag(controller: "category_products", action: "nuevocategoria", method: "post") do %>
		<div class="field">
		  <%= text_field_tag(:categoria, "", placeholder: "Nueva Categoria",required: "")  %>
		</div>
		  <%= submit_tag("Crear", class: 'btn') %>
		<% end %>
		<%= form_tag(controller: "branding_products", action: "nuevomarca", method: "post") do %>
		<div class="field">
		  <%= text_field_tag(:marca, "", placeholder: "Nueva Marca",required: "" ) %>
		</div>
		  <%= submit_tag("Crear", class: 'btn') %>
		<% end %>
	</div>

<h1>NUEVO PRODUCTO</h1>

	<%= render 'form' %>

<em><%= link_to 'Ver Todos los productos', products_path %></em>

</section>